<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxs1q9l\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxs1q9l/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxs1q9l.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxs1q9l\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxs1q9l\appProdProjectContainer([
    'container.build_hash' => 'Xxs1q9l',
    'container.build_id' => 'bcd1f314',
    'container.build_time' => 1693481359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxs1q9l');
